# Generated by Django 5.0.3 on 2024-03-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('sender', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('number', models.IntegerField()),
                ('is_done', models.BooleanField(default=False)),
            ],
        ),
    ]
