# Generated by Django 5.0.3 on 2024-03-28 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api_app.author'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='receiver',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_app.user'),
        ),
    ]
