# Generated by Django 5.0.3 on 2024-03-28 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_letter_sender_alter_letter_receiver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letter',
            name='receiver',
        ),
    ]
