# Generated by Django 5.0.3 on 2024-04-02 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0005_tag_letter_receiver_alter_letter_sender_letter_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letter',
            name='tag',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
