# Generated by Django 5.0.3 on 2024-05-22 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0007_tag_letter_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='firebase_id',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
    ]
